# Generated by Django 5.0 on 2024-04-15 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacks', '0002_initial'),
        ('scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='liquidfeedbackscore',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.score', verbose_name='Рейтинг пользователя'),
        ),
        migrations.AddField(
            model_name='userfeedbackscore',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.feedback', verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='userfeedbackscore',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.score', verbose_name='Рейтинг пользователя'),
        ),
    ]
