# Generated by Django 5.0 on 2024-04-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='userfeedbackscore',
            options={'verbose_name': 'Рейтинг отзыва', 'verbose_name_plural': 'Рейтинги отзывов'},
        ),
    ]
