# Generated by Django 5.0 on 2024-04-16 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_alter_feedback_options'),
        ('scores', '0003_alter_score_options_alter_userfeedbackscore_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbackscore',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_feedbacks', to='feedbacks.feedback', verbose_name='Отзыв'),
        ),
    ]
