# Generated by Django 5.0 on 2024-04-16 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquids', '0003_alter_liquid_manufacturer'),
        ('scores', '0004_alter_userfeedbackscore_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidfeedbackscore',
            options={'verbose_name': 'Рейтинг жидкости', 'verbose_name_plural': 'Рейтинги жидкостей'},
        ),
        migrations.AlterField(
            model_name='liquidfeedbackscore',
            name='liquid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquids_feedbacks', to='liquids.liquid', verbose_name='Жидкость'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
