# Generated by Django 5.0 on 2024-04-15 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerLiquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Название изготовителя жидкости')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название жидкости')),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Крепкость')),
                ('cold', models.BooleanField(default=False, verbose_name='Холодок')),
                ('taste', models.CharField(max_length=200, verbose_name='Вкус')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquids.manufacturerliquid', verbose_name='Изготовитель жидкости')),
            ],
        ),
    ]
