# Generated by Django 5.0 on 2024-04-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquids', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquid',
            options={'verbose_name': 'Жидкость', 'verbose_name_plural': 'Жидкости'},
        ),
        migrations.AlterModelOptions(
            name='manufacturerliquid',
            options={'verbose_name': 'Изготовитель жидкости', 'verbose_name_plural': 'Изготовители жидкости'},
        ),
    ]
