# Generated by Django 5.0 on 2024-04-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquids', '0002_alter_liquid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquids', to='liquids.manufacturerliquid', verbose_name='Изготовитель жидкости'),
        ),
    ]
