# Generated by Django 5.0 on 2024-04-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquids', '0003_alter_liquid_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquid',
            name='name',
        ),
    ]
