# Generated by Django 5.0 on 2024-04-15 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('vapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='vape_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapes.vapeprofile', verbose_name='Вэйп'),
        ),
    ]
