# Generated by Django 5.0 on 2024-04-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_alter_feedback_options'),
        ('liquids', '0003_alter_liquid_manufacturer'),
        ('vapes', '0003_alter_vape_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='liquid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='liquids.liquid', verbose_name='Жидкость'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='vape_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='vapes.vapeprofile', verbose_name='Вэйп'),
        ),
    ]
