# Generated by Django 5.0 on 2024-04-15 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerVape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Название изготовителя девайса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Vape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название девайса')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapes.manufacturervape', verbose_name='Изготовитель девайса')),
            ],
        ),
        migrations.CreateModel(
            name='VapeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Статья')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vape_profiles', to='profiles.profile', verbose_name='Профиль пользователя')),
                ('vape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapes.vape', verbose_name='Вэйп')),
            ],
        ),
    ]
