# Generated by Django 5.0 on 2024-04-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturervape',
            options={'verbose_name': 'Изготовитель вэйпа', 'verbose_name_plural': 'Изготовители вэйпа'},
        ),
        migrations.AlterModelOptions(
            name='vape',
            options={'verbose_name': 'Вэйп', 'verbose_name_plural': 'Вэйпы'},
        ),
        migrations.AlterModelOptions(
            name='vapeprofile',
            options={'verbose_name': 'Вэйп-профайл', 'verbose_name_plural': 'Вэйп-профайлы'},
        ),
    ]
