# Generated by Django 5.0 on 2024-04-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapes', '0002_alter_manufacturervape_options_alter_vape_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vape',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vapes', to='vapes.manufacturervape', verbose_name='Изготовитель девайса'),
        ),
    ]
