# Generated by Django 5.0.4 on 2024-05-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_options'),
        ('vapes', '0003_alter_vape_manufacturer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vapeprofile',
            unique_together={('profile', 'vape')},
        ),
    ]
